# Site settings
title: Canada Jukebox
author:
  name: Glen Smith
  email: glensmithmail@yahoo.ca
description: "A diary of Canadian Rock and Roll."

# Build settings
remote_theme: pmarsceill/just-the-docs

# Color scheme supports "light" (default) and "dark"
color_scheme: dark
